#!/bin/bash

docker-compose -f docker-compose-test.yml build
docker-compose -f docker-compose-test.yml up --remove-orphans & # Run in the background
sleep 10 # Wait for 10 seconds
go test -v ./...
docker-compose -f docker-compose-test.yml down
